name: Create static redbean server
description: "Create a single-file cross-platform server within an executable ZIP, powered by redbean"

inputs:
  version:
    description: "Redbean executable to download & use"
    default: "latest"
  executable-name:
    description: "Name of the redbean executable"
    default: "redbean.com"
  input:
    description: "Location of static files to include"
    default: "dist"
    
runs:
  using: "composite"
  steps:
    - run: echo "::set-output name=executable::$(pwd)/${{ inputs.executable-name }}"
      shell: bash
      id: paths
    - run: curl "https://redbean.dev/redbean-${{ inputs.version }}.com" >"${{ steps.paths.outputs.executable }}"
      shell: bash
    - run: zip -qq -r "${{ steps.paths.outputs.executable }}" ./**
      shell: bash
      working-directory: ${{ inputs.input }}
