name: Create static redbean server
description: "Create a single-file cross-platform server within an executable ZIP, powered by redbean"
inputs:
  version:
    description: "Redbean executable to download & use"
    default: "latest"
  executable-name:
    description: "Name of the redbean executable"
    default: "redbean.com"
  input:
    description: "Location of static files to include"
    default: "dist"
runs:
  using: "composite"
  steps:
    - run: curl "https://redbean.dev/redbean-${{ inputs.version }}.com" >"${{ inputs.executable-name }}"
      shell: bash
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r "${{ inputs.executable-name }}" **
        working-directory: ${{ inputs.input }}
